name: Run Test Script

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-test-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Make test.sh executable
        run: chmod +x ./test.sh

      - name: setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Install Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install -y iproute2
            sudo systemctl start docker || sudo service docker start

      - name: Build
        run: make docker-run-host
